// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Model.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<CoursePackage> CoursePackages { get; set; }

    public virtual DbSet<Lecture> Lectures { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<Unit> Units { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserCourse> UserCourses { get; set; }

    public virtual DbSet<UserLecture> UserLectures { get; set; }

    public virtual DbSet<Year> Years { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Courses__3214EC0711B7097E");

            entity.HasOne(d => d.Year).WithMany(p => p.Courses).HasConstraintName("FK__Courses__YearId__3E52440B");
        });

        modelBuilder.Entity<CoursePackage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CoursePa__3214EC0778A69DF8");

            entity.HasOne(d => d.Course).WithMany(p => p.CoursePackages).HasConstraintName("FK__CoursePac__Cours__4AB81AF0");

            entity.HasOne(d => d.Package).WithMany(p => p.CoursePackages).HasConstraintName("FK__CoursePac__Packa__49C3F6B7");
        });

        modelBuilder.Entity<Lecture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Lectures__3214EC07F58FA318");

            entity.HasOne(d => d.Course).WithMany(p => p.Lectures).HasConstraintName("FK__Lectures__Course__412EB0B6");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Lectures).HasConstraintName("FK_Lectures_TeacherId");

            entity.HasOne(d => d.Unit).WithMany(p => p.Lectures).HasConstraintName("FK_Lectures_Unit");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Packages__3214EC079D85FF00");
        });

        modelBuilder.Entity<Unit>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Units__3214EC0716593EA4");

            entity.HasOne(d => d.Course).WithMany(p => p.Units).HasConstraintName("FK_Units_Course");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3214EC0702DAC5F2");

            entity.Property(e => e.RegisterDate).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UserCourse>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserCour__3214EC07D5A12AB8");

            entity.HasOne(d => d.Course).WithMany(p => p.UserCourses).HasConstraintName("FK__UserCours__Cours__44FF419A");

            entity.HasOne(d => d.User).WithMany(p => p.UserCourses).HasConstraintName("FK__UserCours__UserI__440B1D61");
        });

        modelBuilder.Entity<UserLecture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserLect__3214EC07155C924D");

            entity.HasOne(d => d.Lecture).WithMany(p => p.UserLectures).HasConstraintName("FK__UserLectu__Lectu__59FA5E80");

            entity.HasOne(d => d.User).WithMany(p => p.UserLectures).HasConstraintName("FK__UserLectu__UserI__59063A47");
        });

        modelBuilder.Entity<Year>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Years__3214EC0795A49E79");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}