// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class Course
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Descryption { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Price { get; set; }

    public int? Order { get; set; }

    public int? TeacherId { get; set; }

    public int? YearId { get; set; }

    public virtual ICollection<CoursePackage> CoursePackages { get; set; } = new List<CoursePackage>();

    public virtual ICollection<Lecture> Lectures { get; set; } = new List<Lecture>();

    public virtual ICollection<UserCourse> UserCourses { get; set; } = new List<UserCourse>();

    public virtual Year Year { get; set; }
}