// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class CoursePackage
{
    public int Id { get; set; }

    public int? PackageId { get; set; }

    public int? CourseId { get; set; }

    public virtual Course Course { get; set; }

    public virtual Package Package { get; set; }
}