// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class Lecture
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime? Date { get; set; }

    public string Url { get; set; }

    public string Descryption { get; set; }

    public int? Order { get; set; }

    public int? CourseId { get; set; }

    public int? TeacherId { get; set; }

    public decimal? Price { get; set; }

    public virtual Course Course { get; set; }

    public virtual User Teacher { get; set; }

    public virtual ICollection<UserLecture> UserLectures { get; set; } = new List<UserLecture>();
}