// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class Package
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Descryption { get; set; }

    public decimal? Price { get; set; }

    public virtual ICollection<CoursePackage> CoursePackages { get; set; } = new List<CoursePackage>();
}