// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Model.Data;

public partial class Unit
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    public string Description { get; set; }

    public int CourseId { get; set; }

    public int OrderNumber { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("Units")]
    public virtual Course Course { get; set; }

    [InverseProperty("Unit")]
    public virtual ICollection<Lecture> Lectures { get; set; } = new List<Lecture>();
}