// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class UserLecture
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? LectureId { get; set; }

    public virtual Lecture Lecture { get; set; }

    public virtual User User { get; set; }
}