// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class Year
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Descryption { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}